# Generated by Django 5.1.4 on 2024-12-12 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_course_course_ref_alter_course_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_Ref',
            field=models.UUIDField(default=uuid.UUID('4f3fbdc2-c3ff-444d-8562-12bf508f9a8c'), unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_Ref',
            field=models.UUIDField(default=uuid.UUID('9a92746a-4dc7-4b3c-8b9c-e8c25e743fd6'), unique=True),
        ),
    ]
