# Generated by Django 5.1.4 on 2024-12-12 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_course_course_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_Ref',
            field=models.UUIDField(default=uuid.UUID('fdf77556-5270-4276-bb20-61d7e7d40c79'), unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_Ref',
            field=models.UUIDField(default=uuid.UUID('f8b8d646-a6dd-47a9-8698-14494c160c35'), unique=True),
        ),
    ]
