# Generated by Django 5.1.4 on 2024-12-12 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_course_course_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_Id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Ref',
            field=models.UUIDField(default=uuid.UUID('1640bb6c-a80d-4f8e-8118-3ffc63843225'), unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_Id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_Ref',
            field=models.UUIDField(default=uuid.UUID('c9dfe502-cb1e-4a10-8e98-cebef01d98c7'), unique=True),
        ),
    ]
