# Generated by Django 5.1.4 on 2024-12-12 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_course_course_id_alter_course_course_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_Id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Ref',
            field=models.UUIDField(default=uuid.UUID('c65a00a7-99c3-419a-9971-9f61a47633bf'), unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_Ref',
            field=models.UUIDField(default=uuid.UUID('a01f4b24-39f2-4ad2-9b67-94ffe3848033'), unique=True),
        ),
    ]
