# Generated by Django 5.1.4 on 2024-12-13 04:39

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_course_course_id_alter_course_course_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetailsModels',
            fields=[
                ('course_Ref', models.UUIDField(default=uuid.UUID('6ff84852-76c0-432a-af27-dfe627db8c47'), unique=True)),
                ('course_Id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('course_Name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, choices=[('BASICS', 'basic'), ('ADVANCED', 'advanced'), ('PLACEMENT', 'placement')], null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('tools_Technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=100), size=None)),
                ('concept', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=100), size=None)),
                ('includes_Internship', models.BooleanField(blank=True, default=False)),
                ('includes_Placement', models.BooleanField(blank=True, default=False)),
                ('shift_Available', models.CharField(blank=True, choices=[('morning', 'Morning '), ('afternoon', 'Afternoon '), ('weekend', 'weekend')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetailsModels',
            fields=[
                ('student_Ref', models.UUIDField(default=uuid.UUID('cb123eeb-6ce4-4e39-8bb6-63204307f4e5'), unique=True)),
                ('student_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('student_Fullname', models.CharField(max_length=100)),
                ('student_Email', models.EmailField(max_length=254, unique=True)),
                ('student_Mobile', models.BigIntegerField()),
                ('student_Dob', models.CharField(blank=True, max_length=50, null=True)),
                ('student_Location', models.CharField(max_length=50)),
                ('student_Occupation', models.CharField(choices=[('student', 'student'), ('working professional', 'working professional'), ('freelancer', 'freelancer'), ('other', 'other')])),
                ('student_Other', models.CharField(blank=True, null=True)),
                ('student_intrest', models.CharField(blank=True, null=True)),
                ('student_Organization', models.CharField(blank=True, max_length=200, null=True)),
                ('student_Ai_Ml', models.BooleanField(default=False)),
                ('student_Experience', models.TextField(blank=True, null=True)),
                ('student_Learn', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=100, null=True), size=None)),
                ('student_Timming', models.CharField(blank=True, choices=[('morning', 'Morning (9:00 AM - 12:30 PM)'), ('afternoon', 'Afternoon (1:30 PM - 5:30 PM)'), ('full_day', 'Full Day (9:00 AM - 5:30 PM)')], max_length=50, null=True)),
                ('student_Payment', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
