# Generated by Django 5.1.4 on 2024-12-13 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_coursedetailsmodels_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailsmodels',
            name='course_Ref',
            field=models.UUIDField(default=uuid.UUID('06c200d2-2477-438e-baef-b55ea992068b'), unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetailsmodels',
            name='student_Ref',
            field=models.UUIDField(default=uuid.UUID('c36e1400-8804-4b69-9dc5-83fef0ab7927'), unique=True),
        ),
    ]
